---
- name: Install Bind9 Server
  apt: pkg=bind9
- name: Configure Bind Options
  template: src=named.conf.options.j2 dest=/etc/bind/named.conf.options group=bind
  notify: Restart Bind
- name: Configure Bind Local
  template: src=named.conf.local.j2 dest=/etc/bind/named.conf.local group=bind
  notify: Restart Bind
- name: Configure subnets
  template: src=subnet.hosts.j2 dest=/var/lib/bind/{{ item.key }}.hosts group=bind mode=6600
  with_dict: subnets
  notify: Restart Bind
- name: Configure RDNS for subnets
  template: src=rdns.rev.j2 dest=/var/lib/bind/{{ item.value.reverse }}.rev group=bind mode=660
  with_dict: subnets
  notify: Restart Bind
- name: Ensure /var/lib/bind is owned by Bind
  file: path=/var/lib/bind owner=bind group=bind recurse=yes state=directory
