---
- name: Install DHCP Server
  apt: pkg=isc-dhcp-server state=latest update_cache=yes
- name: Configure DHCP
  template: src=dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf
  with_items: developers
  notify: Restart DHCP
